### ISSUE TITLE
`TodoTemplate` project has some serious issues

### ISSUE THREAD

**Issue by mhrastegari** [bitfoundation/bitplatform#3825] opened 2023-01-28 21:25 UTC
- Sorting is not working
- Completed item shows in active section
- When you check and uncheck a todo item after editing it, it refreshes the list each time
- After edit an item when you check another item, it gets the edited item's content
- When you refresh the page items will be unchecked

**Comment by msynk** [comment] 2023-01-28 21:33
I believe all of these issues have been fixed recently.
could you plz double-check and confirm?

https://todo.bitplatform.dev

**Comment by mhrastegari** [comment] 2023-01-28 21:37
yup still there :)

**Comment by msynk** [comment] 2023-01-28 21:57
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment] 2023-01-28 21:57
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment] 2023-01-28 23:27
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment] 2023-01-29 00:04
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Closed** 2023-01-29 00:04 UTC
Labels: area / templates

**Comment by msynk** [comment] 2023-02-07 23:37
The pre-release has been published. Please give it a try and give feedback.
