### ISSUE TITLE
Failed Unit Test of the `BitRating` component

### ISSUE THREAD

**Issue by SomayeEbrahimi** [bitfoundation/bitplatform#431] opened 2021-06-01 09:52 UTC
The issue is on "BitRatingShouldRespectClickIndex" test

**Comment by msynk** [comment] 2021-06-01 10:40
It appears that the issue is somewhere in the bUnit framework. as I investigated the issue, apparently the component works well on the consumer side (for example in Component.razor), but in the test, there is a wired behaviour of the bUnit itself which is making the 2-way bound parameter to be reset multiple times.

**Comment by zoha-shobbar** [comment] 2021-09-23 17:04
this issue is handled in pull request #833  and the part of the bUnit issue get comment until it gets solved

**Comment by msynk** [comment] 2023-06-06 16:01
since it is somehow resolved now, I'm closing this issue.

**Closed by msynk** 2023-06-06 16:01 UTC
Labels: area / components, enhancement
