### ISSUE TITLE
BitNav - Possibility to render a custom component

### ISSUE THREAD

**Issue by biohazard999** [bitfoundation/bitplatform#4800] opened 2023-07-22 09:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Currently it's only possible to change the `ItemTemplate` for what get's rendered inside the `button` or `a` element.

I have a scenario where i want to render a custom component (a calendard component) inside a group of the BitNav. 

### Describe the solution you'd like

Suggestion: add a `ButtonTemplate` that gets optionally rendered when set.

**Comment by msynk** [comment] 2023-07-22 10:10
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment] 2023-07-22 10:23
@biohazard999 
Could you please provide an image (and a pseudo-code if possible) of what you want to achieve with the BitNav?
Since BitNav is a complex component with 3 different APIs to accept inputs, I want to know what is missing in detail.

**Comment by msynk** [comment] 2023-07-22 10:40
btw, I've managed to achieve something like this:

![image](https://github.com/bitfoundation/bitplatform/assets/6169846/ad56e292-6e7b-47ca-bed6-38ec74133933)

with this code:

![image](https://github.com/bitfoundation/bitplatform/assets/6169846/5eb8c12b-0baf-40bf-861b-67e310189dfd)

**Comment by biohazard999** [comment] 2023-07-22 12:05
@msynk  The problem lies primarily in the fact that you must not render interactive controls inside of a `button` element.

I got it to work like in your example, but i don't think it's a good practice (and semantically it's wrong).

<img width="766" alt="image" src="https://github.com/bitfoundation/bitplatform/assets/653905/5236f047-f3f8-46a7-861c-b7ef96a6fc8d">


<img width="224" alt="image" src="https://github.com/bitfoundation/bitplatform/assets/653905/2ea1b97e-530e-404f-ba29-8d46a836c456">

<img width="454" alt="image" src="https://github.com/bitfoundation/bitplatform/assets/653905/8b4dbbae-0d75-40a5-b5c9-b8285d70cd34">

For the pseudo code it's basically the same as the `ItemTemplate`

```razor
<BitNav>
    <ButtonTemplate Context="item">
        @if(item.Name == "Foo")
        {
            <MyComponent />
        }
    </ButtonTemplate>
    <ItemTemplate>
        @* This would not have any effect *@
    </ItemTemplate>
<BitNav>
```

Another suggestion would be to extend the `ForceAnchor` to be an enumeration like the `RenderType`.

I understand that it is a complex component with several API's. I might provide a PR if this is considered to be a valuable feature for the product

**Comment by biohazard999** [comment] 2023-07-22 12:09
Another idea would be to provide the `BitNavItem` and the other API's to provide it's own `RenderFragment` property that has a higher priority when rendered.

**Comment by msynk** [comment] 2023-07-22 13:13
@biohazard999 
Thanks for the clarification. I now see what is missing.

**Comment by msynk** [comment] 2023-07-22 13:14
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment] 2023-07-24 17:59
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment] 2023-07-24 22:52
@biohazard999 
the PR is under review, you can check it out and post your review comments too:

https://github.com/bitfoundation/bitplatform/pull/4821

**Comment by msynk** [comment] 2023-07-25 08:37
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Closed** 2023-07-25 08:37 UTC
Labels: area / components

**Comment by msynk** [comment] 2023-07-28 07:19
The pre-release has been published. Please give it a try and give feedback.

**Comment by biohazard999** [comment] 2023-07-28 08:00
@msynk 

```razor
    return new BitNavItem()
    {
        Key = navItem.Id,
        TemplateRenderMode = BitNavItemTemplateRenderMode.Replace,
        Template = _ => @<MyComponent />
    };
```

did the trick, perfect thanks :)

**Comment by msynk** [comment] 2023-07-28 08:08
Glad to hear that this helped.
Thanks for choosing the Bit Platform products.
