### ISSUE TITLE
Need swiper for swipe between card

### ISSUE THREAD

**Issue by hootanht** [bitfoundation/bitplatform#2748] opened 2022-07-25 08:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/27281206/180731085-d388be17-c36d-4f01-9b86-d9e12ba7b444.png)

We need a swiper like this, I think this carousel is used `swiperjs` library and we don't have this feature in Bit Platform

**Comment by msynk** [comment] 2022-07-25 09:03
@hootanht 
isn't this a duplicate of #2717?
if it's not, please provide more information

**Comment by hootanht** [comment] 2022-07-25 10:31
> @hootanht isn't this a duplicate of #2717? if it's not, please provide more information

yes

**Comment by msynk** [comment] 2022-07-25 11:15
Since it's a duplicate of #2717, I'm closing this issue.

**Closed by msynk** 2022-07-25 11:15 UTC
