### ISSUE TITLE
`UserSecretsId` is not unqiue for each generated project

### ISSUE THREAD

**Issue by hamedhajiloo** [bitfoundation/bitplatform#6634] opened 2024-01-19 20:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When we create a project based on Bitplatform templates, the UserSecretsId in Server project is duplicated.

### Expected Behavior

In this scenario must generate a new UserSecretsId for every new project.

**Comment by msynk** [comment] 2024-01-20 05:00
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue.

**Comment by msynk** [comment] 2024-01-20 11:32
The issue is accepted and planned. Resolving it will start ASAP.
btw, a PR from you is welcome for this.

**Closed** 2024-01-20 13:20 UTC
Labels: area / templates

**Comment by msynk** [comment] 2024-05-23 20:39
The pre-release has been published. Please give it a try and give feedback.
