### ISSUE TITLE
Expose the indexer of Internal loop of the `ChoiceGroup` Items

### ISSUE THREAD

**Issue by samdubey** [bitfoundation/bitplatform#5606] opened 2023-10-17 09:28 UTC
Dear Team,

We need to have access to the internal counter/indexer value of each item in the internal loop of the ChoiceGroup for adding our own indexing numbers in the UI like this:

![image](https://github.com/bitfoundation/bitplatform/assets/6169846/67d35de5-9f43-443d-b6b9-7c498802361f)

**Comment by msynk** [comment] 2023-10-17 09:54
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue.

**Comment by msynk** [comment] 2023-10-17 09:55
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment] 2023-10-17 15:10
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment] 2023-10-17 16:27
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Closed** 2023-10-17 16:26 UTC
Labels: area / BlazorUI

**Comment by msynk** [comment] 2023-10-17 19:35
The pre-release has been published. Please give it a try and give feedback.
