### ISSUE TITLE
the default pointer-events of any img tag should be none in BitCarousel

### ISSUE THREAD

**Issue by mhrastegary77** [bitfoundation/bitplatform#2824] opened 2022-07-30 19:29 UTC
when we swipe/drag on BitCarousel the image of item will be dragged out of it like getting a copy of it.
because of that i think we should define something like :
`::deep img {
    pointer-events: none;
}
`

**Comment by msynk** [comment] 2022-07-30 21:55
We're investigating your issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment] 2022-07-30 21:57
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment] 2022-07-30 21:58
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by mhrastegary77** [comment] 2022-07-31 01:34
Thanks :)❤️

**Comment by msynk** [comment] 2022-07-31 05:14
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Closed** 2022-07-31 05:14 UTC
Labels: area / components

**Comment by msynk** [comment] 2022-08-14 09:52
The pre-release has been published. Please give it a try and give feedback.
