### ISSUE TITLE
Misleading documentation of BitDataGrid component

### ISSUE THREAD

**Issue by ShahryarSaljoughi** [bitfoundation/bitplatform#7770] opened 2024-06-12 09:02 UTC
*Short summary (3-5 sentences) describing the issue.*
I thought I could pass the `Visibility` parameter of `BitComponentBase` to a `BitDataGrid` component. I failed since in despite of all Bit.BlazorUI components, BitDataGrid is not inheriting from `BitComponentBase`. I guess it would be more correct not to mention list the properties of `BitComponentBase` within the docs of `BitDataGrid` component, as it may give the idea that there is inheritance between these two.

**Comment by msynk** [comment] 2024-06-12 20:39
@ShahryarSaljoughi Thanks for finding this problem.

The issue is accepted and planned. Resolving it will start ASAP.

**Closed** 2024-06-13 17:59 UTC
Labels: area / BlazorUI
