### ISSUE TITLE
the `IServer` interface dos not show the host URL in the Linux server

### ISSUE THREAD

**Issue by Cyrus-Sushiant** [bitfoundation/bitplatform#1994] opened 2022-05-10 17:02 UTC
we need to research to find out if there is a solution to get the host URL in Linux using the `IServer` interface?

![image](https://user-images.githubusercontent.com/29052211/167683205-726474d2-97ed-4072-9ade-b3967076ff6f.png)

**Comment by sajadkardel** [comment] 2022-05-25 10:28
For this issue, we must first add a Linux server in the Azure settings and then test whether the problem is solved or not.

**Comment by sajadkardel** [comment] 2022-06-06 01:26
1. I wrote a separate API application with only one API that returns the host uri.

> <img width="412" alt="IServer-code" src="https://user-images.githubusercontent.com/62190682/172077535-8a754051-661d-46d0-ba82-082bf5fa28e1.png">
> 
> To get the host uri from IServer interface, I created a new extensions class named by IServerExtensions, And then I wrote the following method inside it
> 
> <img width="519" alt="Untitled" src="https://user-images.githubusercontent.com/62190682/172077905-128bfd60-0bf6-4ca0-a0a9-a6e6c480c395.png">


2. Next, I created a Windows server in Azure and published the application on it. Everything worked properly :

> <img width="449" alt="windows-Server" src="https://user-images.githubusercontent.com/62190682/172077411-84e12ebf-931e-45e5-b3be-333f74544d02.png">

3.  I created a Linux server in Azure and published the application on it. But the response was as follows :

> <img width="391" alt="linux responsepng" src="https://user-images.githubusercontent.com/62190682/172078117-f765ad9b-9ec7-408c-a907-76d38c4e387e.png">
> 
> I searched for this but have not found the answer for the IServer interface.

4. In the next step I tried to find another way to get host uri. I used `IHttpContextAccessor` interface.

> first, I added this interface to my controller injected properties :
> <img width="516" alt="Untitled" src="https://user-images.githubusercontent.com/62190682/172078862-f460fd18-a031-4fc8-b717-df70f9b8dadf.png">
> 
> and then, I created `IHttpContextExtensions` class with `GetHostUri()` method :
> <img width="477" alt="Untitled" src="https://user-images.githubusercontent.com/62190682/172079046-739be728-037b-46a6-8983-dcb3af24605e.png">
> 
> in the end, My API code is as follows :
> <img width="599" alt="Untitled" src="https://user-images.githubusercontent.com/62190682/172079199-743fff92-40b6-46a6-b924-0c9b4832e33d.png">

5. I published the application on the Linux server and the response was as follows :

> <img width="630" alt="Untitled" src="https://user-images.githubusercontent.com/62190682/172079455-20be3f11-0bda-4246-84e7-4d4dae020012.png">

> As you can see, the IHttpContextExtensions interface works fine. 

But now the question is whether we want to use this approach or not?
I think you have to decide @ysmoradi @msynk

**Comment by ysmoradi** [comment] 2022-06-06 05:23
I was aware that we could use HTTP context, but the question is, is it possible to get the server address from `IServer`?
How many addresses does it have in `.Addresses` property of `IServerAddressesFature`?
@sajadkardel

**Comment by msynk** [comment] 2022-06-09 06:46
I think the IServer issue can be addressed in a separate issue, for this issue I suggest we use the base64 value of the logo image itself.
@sajadkardel 
@maryamhdr

**Comment by ysmoradi** [comment] 2022-06-09 09:03
As far as I've heard from @Cyrus-Sushiant there are some issues with base64 in emails
@msynk

**Comment by msynk** [comment] 2022-06-09 10:19
> As far as I've heard from @Cyrus-Sushiant there are some issues with base64 in emails @msynk

maybe this helps:

https://stackoverflow.com/questions/9110091/base64-encoded-images-in-email-signatures

@ysmoradi 
@Cyrus-Sushiant 
@sajadkardel 
@maryamhdr

**Comment by Cyrus-Sushiant** [comment] 2022-06-09 10:21
> > As far as I've heard from @Cyrus-Sushiant there are some issues with base64 in emails @msynk
> 
> maybe this helps:
> 
> https://stackoverflow.com/questions/9110091/base64-encoded-images-in-email-signatures
> 
> @ysmoradi @Cyrus-Sushiant @sajadkardel @maryamhdr

I tested. it did not work.

**Comment by msynk** [comment] 2022-06-09 12:05
how about these:

https://stackoverflow.com/questions/15344555/email-with-digital-signature-and-embedded-image
https://www.emailarchitect.net/easendmail/kb/csharp.aspx?cat=8

@Cyrus-Sushiant

**Comment by maryamhdr** [comment] 2022-06-14 06:04
Since the investigation into this issue is over, I will close it :)

**Closed by maryamhdr** 2022-06-14 06:04 UTC
Labels: area / project template, enhancement
