### ISSUE TITLE
`BitDatePicker` style issue in small screens

### ISSUE THREAD

**Issue by msangtarash** [bitfoundation/bitplatform#3424] opened 2022-10-23 15:04 UTC
![image](https://user-images.githubusercontent.com/23101977/197399582-8fe2fcc5-1235-4064-8225-5e44a70e3ae2.png)

**Comment by msynk** [comment] 2022-10-23 18:30
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment] 2022-10-29 13:30
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment] 2022-11-07 06:55
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment] 2022-11-08 10:51
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Closed** 2022-11-08 10:50 UTC
Labels: area / components

**Comment by msynk** [comment] 2022-11-15 18:37
The pre-release has been published. Please give it a try and give feedback.
