### ISSUE TITLE
Bit UI Components CheckBox demo

### ISSUE THREAD

**Issue by ajafarip** [bitfoundation/bitplatform#3160] opened 2022-09-01 15:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

when you click on "Indeterminated checkbox" in the Indeterminate section, the "Basic checkbox" from the BitCheckbox section it checked.
https://components.bitplatform.dev/components/check-box

### Expected Behavior

They should work independently on the demo page.

**Comment by ysmoradi** [comment] 2022-09-01 16:48
We're investigating your issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment] 2022-09-01 17:03
@ajafarip Thank you for submitting this issue.
I think it was intended.
But with the new improvements it should be changed in a way that the examples do not interfere with each other.
I'm closing this issue since it's not an actual issue and we are going to address it in some way in the checkbox improvements refactoring in the future.

**Closed by msynk** 2022-09-01 17:03 UTC
