### ISSUE TITLE
`BitCheckBox` with image

### ISSUE THREAD

**Issue by msangtarash** [bitfoundation/bitplatform#3494] opened 2022-11-06 11:23 UTC
I need to show the image instead of the check box to show checked items.

![image](https://user-images.githubusercontent.com/23101977/200167745-500fb03e-7c4e-4644-ab93-0349a4a59b9b.png)

**Comment by msynk** [comment] 2022-11-07 06:54
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment] 2022-11-08 10:32
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment] 2022-11-08 11:35
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment] 2022-11-10 14:41
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Closed** 2022-11-10 14:41 UTC
Labels: area / components

**Comment by msynk** [comment] 2022-11-15 21:02
The pre-release has been published. Please give it a try and give feedback.
