### ISSUE TITLE
`BitDropDown` : Remove z-index from bit-drp-wrapper class

### ISSUE THREAD

**Issue by mhrastegari** [bitfoundation/bitplatform#2987] opened 2022-08-13 12:59 UTC
### Summary
z-index in [this style class](https://github.com/bitfoundation/bitplatform/blob/ec3ee93930457f358524d29645533e645f79f4e1/src/BlazorUI/Bit.BlazorUI/Components/DropDown/BitDropDown.Fluent.scss#L204) should be removed, because I see sort drop down is on the higher stack order than navmenu in todo template.

### Reproduce steps
open BitTodoTemplate in a small screen
open NavMenu
you can see the sort drop down is on the higher stack order than navmenu.

**Comment by ysmoradi** [comment] 2022-08-13 13:30
We're investigating your issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment] 2022-08-15 08:45
@mhrastegary77 
isn't this a duplicate of #2692?

**Comment by mhrastegary77** [comment] 2022-08-15 09:56
Yes

**Comment by msynk** [comment] 2022-09-15 15:08
duplicate of #2692

**Closed by msynk** 2022-09-15 15:08 UTC
