### ISSUE TITLE
The Breadcrumb component does not display the current item correctly

### ISSUE THREAD

**Issue by MeysamBahadori** [bitfoundation/bitplatform#3597] opened 2022-12-05 09:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The Breadcrumb  component does not display the current item correctly and only displays the last item as current.
I set the IsCurrentItem property of the BitBreadcrumbItem to true but it does not have any effect

### .NET Version

7

### Anything else?

Bit.BlazorUI => 4.8.0

**Comment by msynk** [comment] 2022-12-05 11:38
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment] 2022-12-06 15:24
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment] 2022-12-06 15:25
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment] 2022-12-06 19:05
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Closed** 2022-12-06 19:04 UTC
Labels: area / components

**Comment by msynk** [comment] 2023-02-07 23:35
The pre-release has been published. Please give it a try and give feedback.
