### ISSUE TITLE
Typo in the docs

### ISSUE THREAD

**Issue by fateme12** [bitfoundation/bitplatform#7439] opened 2024-05-03 19:34 UTC
### Typographical Mistake
There is a typographical mistake in the documents. In the App Models section, the first paragraph of the Blazor Webassembly description is written "To use to Blazor WebAssembly" which should be "To use the Blazor WebAssembly".

**Comment by fateme12** [comment] 2024-05-03 19:44
Another Typographical Mistake in the same section is in the first paragraph of the Blazor Auto description. It should be "To use the Blazor Auto" instead of "To use to Blazor Auto".

**Comment by msynk** [comment] 2024-05-04 17:43
@fateme12 Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue.

**Comment by msynk** [comment] 2024-05-04 17:44
The issue is accepted and planned. Resolving it will start ASAP.

**Closed** 2024-08-08 08:26 UTC
Labels: area / websites, good first issue
