### ISSUE TITLE
customizing the  Start and End labels and icon issue in DateRangePicker

### ISSUE THREAD

**Issue by MeysamBahadori** [bitfoundation/bitplatform#3438] opened 2022-10-24 07:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Is there a way to customize the Start and End labels in DateRangePicker?
![image](https://user-images.githubusercontent.com/107020266/197470822-ffd87658-3a0a-455a-8f8f-61b90dc5f6bd.png)

Also, is it possible to change the icon and its location (right and left)?

![image](https://user-images.githubusercontent.com/107020266/197471442-ed572b7b-ac23-4e70-a52f-d33c2e53fcee.png)

**Comment by msynk** [comment] 2022-10-24 11:07
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment] 2022-10-29 13:31
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment] 2022-10-29 18:01
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment] 2022-10-31 21:13
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Closed** 2022-10-31 21:13 UTC
Labels: area / components

**Comment by msynk** [comment] 2022-11-15 18:40
The pre-release has been published. Please give it a try and give feedback.
