### ISSUE TITLE
BitDatePicker and BitDateRangePicker Min Max Date issue on Jalali culture

### ISSUE THREAD

**Issue by MeysamBahadori** [bitfoundation/bitplatform#3437] opened 2022-10-24 06:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

when the culture of Bit DateRangePicker is set to fa-Ir the date boundaries feature (Min or Max date) not working and causes the user can not be able to select a date, also it's the same for the DatePicker.
 
![image](https://user-images.githubusercontent.com/107020266/197461339-3eb90e4e-7597-4a31-8d75-754da294761a.png)

  ```
      <BitDateRangePicker Label="تاریخ رفت"
                        FormatDate="yyyy/MM/dd"
                        Culture="CultureInfoHelper.GetFaIrCultureByFarsiNames()"
                        Style="margin-right:200px; max-width: 300px"
                        AriaLabel="تاریخ رفت"
                        Placeholder="تاریخ رفت"
                        GoToToday="امروز"
                        MinDate="DateTimeOffset.Now"
                        @bind-Value="@SelectedDate" />
```

**Comment by msynk** [comment] 2022-10-24 11:02
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment] 2022-10-29 13:31
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment] 2022-11-07 07:02
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment] 2022-11-08 10:54
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Closed** 2022-11-08 10:53 UTC
Labels: area / components

**Comment by msynk** [comment] 2022-11-15 18:38
The pre-release has been published. Please give it a try and give feedback.
