### ISSUE TITLE
BitDateRangePicker Two-way binding does not work.

### ISSUE THREAD

**Issue by MeysamBahadori** [bitfoundation/bitplatform#3390] opened 2022-10-19 07:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

**BitDateRangePicker** Two-way binding does not work.

Also, I saw this problem on the demo page
[Demo Page](https://components.bitplatform.dev/components/date-range-picker#example8)

### .NET Version

6.0.400

### Anything else?

Bit.BlazorUI : 4.4.0-pre-01

**Comment by msynk** [comment] 2022-10-19 10:37
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment] 2022-10-19 17:50
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment] 2022-10-19 21:19
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment] 2022-10-19 21:20
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Closed by msynk** 2022-10-19 21:20 UTC
Labels: bug, area / components

**Comment by msynk** [comment] 2022-10-20 11:48
The pre-release has been published. Please give it a try and give feedback.

**Comment by MeysamBahadori** [comment] 2022-10-22 06:55
Thanks for your responsible follow-up, the issue has been resolved.
