### ISSUE TITLE
Issues of custom ItemLabelTemplate in the `ChoiceGroup`

### ISSUE THREAD

**Issue by samdubey** [bitfoundation/bitplatform#5607] opened 2023-10-17 09:36 UTC
![image](https://github.com/bitfoundation/bitplatform/assets/6169846/ef3b2b98-e31b-4b2c-a7c9-ccd5a2b8af25)

**Comment by msynk** [comment] 2023-10-17 09:54
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue.

**Comment by msynk** [comment] 2023-10-17 09:55
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment] 2023-10-17 17:07
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Closed** 2023-10-17 17:07 UTC
Labels: area / BlazorUI

**Comment by msynk** [comment] 2023-10-17 19:35
The pre-release has been published. Please give it a try and give feedback.
