### ISSUE TITLE
Add direction option for `BitCarousel `

### ISSUE THREAD

**Issue by hootanht** [bitfoundation/bitplatform#2838] opened 2022-07-31 12:18 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

We want to use `BitCarousel` for persian site and we have trouble using this feature in `direction: rtl`.
![image](https://user-images.githubusercontent.com/27281206/182025920-b04e81fa-005d-4817-90ab-08b25d613d5e.png)

### Describe the solution you'd like

We want to use `rtl` in `BitCarousel` and we want to show the first item on the Carousel.

**Comment by msynk** [comment] 2022-07-31 12:57
We're investigating your issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment] 2022-07-31 18:41
The issue is approved. It's waiting to be in progress.

**Comment by msynk** [comment] 2022-08-01 16:33
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment] 2022-08-02 07:08
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Closed** 2022-08-02 07:08 UTC
Labels: area / components, enhancement

**Comment by msynk** [comment] 2022-08-14 09:52
The pre-release has been published. Please give it a try and give feedback.
