### ISSUE TITLE
Boilerplate terminal background color in the Platform website

### ISSUE THREAD

**Issue by hassanyousefi** [bitfoundation/bitplatform#7835] opened 2024-06-23 11:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is an issue on the Bit Platform website homepage within the "Boilerplate" section. The template-terminal's font color is inappropriate when viewed in light mode, making the text difficult to read and affecting the user experience.

### Expected Behavior

The font color should be clearly visible and readable in light mode.

### Steps To Reproduce

Navigate to the Bit Platform website homepage.
Scroll down to the "Boilerplate" section.
Switch to light mode (if not already enabled).
Observe the font color within the template-terminal.

**Comment by msynk** [comment] 2024-06-23 11:26
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue.

**Comment by msynk** [comment] 2024-06-23 11:26
it seems you're right:

![image](https://github.com/bitfoundation/bitplatform/assets/6169846/6e8e1518-59d9-478f-8592-8df447e0c799)

**Comment by msynk** [comment] 2024-06-23 11:27
The issue is accepted and planned. Resolving it will start ASAP.

**Closed** 2024-06-23 13:42 UTC
