### ISSUE TITLE
DataGrid componente handle resize dont work in firefox

### ISSUE THREAD

**Issue by jorge-teixeira** [bitfoundation/bitplatform#5610] opened 2023-10-17 14:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

It seems there is an issue with column resizing in Blazor DataGrids when using Firefox browser. The error Uncaught ReferenceError: TouchEvent is not defined points to an incompatibility with how Firefox handles touch events compared to Edge and other browsers.

### Expected Behavior

Resize collum

### Anything else?

![ezgif com-video-to-gif](https://github.com/bitfoundation/bitplatform/assets/5703266/96fd153d-96fd-47ee-bfd6-38a11d9a92b3)

**Comment by msynk** [comment] 2023-10-17 14:52
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue.

**Comment by jorge-teixeira** [comment] 2023-11-24 09:05
The problem occurred when da DataGrid have a horizontal scrollbar .. if all the column fit the screen/div size all works fine...

**Comment by msynk** [comment] 2024-04-12 09:33
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment] 2024-04-12 09:34
Resolving this issue has started. It will be announced when this issue is resolved.

**Closed** 2024-04-12 10:21 UTC
Labels: area / BlazorUI

**Comment by msynk** [comment] 2024-04-12 10:45
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Comment by msynk** [comment] 2024-05-23 20:37
The pre-release has been published. Please give it a try and give feedback.
