### ISSUE TITLE
`BitRadioButtonList` RTL diraction issue

### ISSUE THREAD

**Issue by msangtarash** [bitfoundation/bitplatform#3492] opened 2022-11-06 10:00 UTC
`BitRadioButtonList` by the direction of RTL is not working fine.

**Comment by msynk** [comment] 2022-11-07 06:35
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment] 2022-11-07 06:35
@msangtarash 
could you plz provide more information?

**Comment by msangtarash** [comment] 2022-11-08 16:36
![image](https://user-images.githubusercontent.com/23101977/200622917-f413d687-cba0-45cb-8474-ea47f00485df.png)

my container direction is RTL
I added the `BitRadioButtonList` into the container.
it is shown like this
even when I set the direction of the main div of the `BitRadioButtonList` to LTR, that doesn't work.

**Comment by msynk** [comment] 2022-11-09 04:47
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment] 2022-11-10 12:05
after some investigations, we decided to add a new parameter named "IsRtl" to the radio button components (like BitDropDown).

**Comment by msynk** [comment] 2022-11-10 12:27
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment] 2022-11-13 10:25
Resolving this issue has started. It will be announced when this issue is resolved.

**Closed** 2022-11-14 09:06 UTC
Labels: area / components

**Comment by msynk** [comment] 2022-11-15 21:04
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Comment by msynk** [comment] 2022-11-15 21:04
The pre-release has been published. Please give it a try and give feedback.
