### ISSUE TITLE
Allow users to change global styles of all components at once

### ISSUE THREAD

**Issue by mhrastegari** [bitfoundation/bitplatform#3338] opened 2022-10-09 19:43 UTC
### Summary
Is it possible to have something like a style configurations file to allow users to change the AccentColor(the default blue color) of all components?
and even other things! like font family, text color and ...

**Comment by msynk** [comment] 2022-10-10 14:28
We're investigating your issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by Kkalinovk** [comment] 2022-11-29 07:32
Is there any update on the topic?

**Comment by msynk** [comment] 2022-11-29 07:37
we are still investigating this issue. the result will be announced soon 😊

**Comment by msynk** [comment] 2022-12-02 08:37
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment] 2022-12-04 18:05
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment] 2022-12-04 19:40
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment] 2023-05-24 23:56
closed by #4436

**Comment by msynk** [comment] 2023-05-24 23:56
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Closed** 2023-05-24 23:57 UTC
Labels: area / components

**Comment by msynk** [comment] 2023-05-25 00:51
The pre-release has been published. Please give it a try and give feedback.
