### ISSUE TITLE
Last digit of `BitOtpInput` stays

### ISSUE THREAD

**Issue by mhrastegari** [bitfoundation/bitplatform#3872] opened 2023-02-05 17:01 UTC
When you fill the OtpInput, the last one when you want to clear stays
![image](https://user-images.githubusercontent.com/42671084/216833301-3f65d500-9b31-45ea-a288-d6e5828a187f.png)

https://components.bitplatform.dev/components/otp-input

it only happens on `Blazor WebAssembly` projects

**Comment by msynk** [comment] 2023-02-06 06:22
I think it's intentional if you're using Backspace to clear the inputs.
Backspace always clears the previous character and not the current one where the cursor is.
You need to use Delete button to remove the current character.

**Comment by mhrastegari** [comment] 2023-02-06 07:28
But phones don't have delete button.

**Comment by msynk** [comment] 2023-02-06 07:30
Yeah, you're right.

**Comment by msynk** [comment] 2023-02-06 09:19
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment] 2023-02-06 09:20
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment] 2023-02-07 18:34
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment] 2023-02-07 19:08
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Closed** 2023-02-07 19:08 UTC
Labels: area / components

**Comment by msynk** [comment] 2023-02-07 23:31
The pre-release has been published. Please give it a try and give feedback.
