### ISSUE TITLE
Add `EmptyContent` to the `BitBasicList` component

### ISSUE THREAD

**Issue by msangtarash** [bitfoundation/bitplatform#5759] opened 2023-10-22 11:28 UTC
We need to show an empty state when there is no item in the list.
https://github.com/dotnet/aspnetcore/pull/49185/commits

**Comment by msynk** [comment] 2023-10-22 14:12
Since this parameter is added in .NET 8 and our product is a multi-TargetFramework library, it is hard to support such a feature.

I suggest manually handling this requirement for now which is easy. You only need to show the empty content when the Items parameter is null or its length is zero, or when the ItemsProvider has a TotalCount of zero.

**Comment by msynk** [comment] 2023-10-22 14:26
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue.

**Comment by msynk** [comment] 2023-10-22 14:28
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment] 2023-10-22 16:46
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment] 2023-10-22 16:54
Resolving this issue has started. It will be announced when this issue is resolved.

**Closed** 2023-10-22 18:51 UTC
Labels: area / BlazorUI

**Comment by msynk** [comment] 2023-12-23 08:35
The pre-release has been published. Please give it a try and give feedback.
