### ISSUE TITLE
Change `BitDropDown` icon issue.

### ISSUE THREAD

**Issue by msangtarash** [bitfoundation/bitplatform#3422] opened 2022-10-23 12:19 UTC
I want to change the icon in  `BitDropDown`

![image](https://user-images.githubusercontent.com/23101977/197391523-a54ab92a-859f-4708-ae8d-bcc95e369b84.png)

 to be able to implement 
 
![image](https://user-images.githubusercontent.com/23101977/197391562-9b656c99-80c4-41d9-9c51-3bac3efdcd5e.png)

but as the content of i is set in the razor I can't change it easily :|

**Comment by msynk** [comment] 2022-10-23 18:30
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment] 2022-10-24 14:58
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment] 2022-10-28 17:15
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment] 2022-10-29 13:08
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Closed** 2022-10-29 13:07 UTC
Labels: area / components

**Comment by msangtarash** [comment] 2022-11-30 14:59
Thank you for the changes :)
