### ISSUE TITLE
In the DateRangePicker component cannot select The current date as the start or end date.

### ISSUE THREAD

**Issue by MeysamBahadori** [bitfoundation/bitplatform#3385] opened 2022-10-18 09:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the **DateRangePicker** component when I need to select a range date between the current day to another date I can not select the current day as the start date, The same is true for the end date, but when the current date is in the middle of the range it's ok

### Expected Behavior

I need to be able to select a range whose start or end can be the current day

### .NET Version

6.0.400

### Anything else?

Bit.BlazorUI : 4.4.0-pre-01
I also saw this problem on the demo components site
[DateRangePicker](https://components.bitplatform.dev/components/date-range-picker)

**Comment by msynk** [comment] 2022-10-18 14:32
Thanks for contacting us. We're investigating your issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment] 2022-10-18 17:22
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment] 2022-10-19 17:56
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment] 2022-10-19 17:56
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Closed** 2022-10-19 17:56 UTC
Labels: area / components

**Comment by msynk** [comment] 2022-10-20 11:47
The pre-release has been published. Please give it a try and give feedback.

**Comment by MeysamBahadori** [comment] 2022-10-22 07:02
The problem has been solved, thank you for your responsibility
