### ISSUE TITLE
DateTime Picker 

### ISSUE THREAD

**Issue by ParsaLmn** [bitfoundation/bitplatform#5422] opened 2023-10-01 09:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi.
When i try to change the time on datepicker with `ShowTimePicker="true"` it also changes the year and month as well while the Culture is set on persian date time.

`<BitDatePicker @bind-Value="@selectedDateTime"
               DateFormat="yyyy/MM/dd HH:mm tt"
               Culture="CultureInfoHelper.GetFaIrCultureByFarsiNames()"
               HighlightSelectedMonth=true
               GoToToday="برو به امروز"
               Style="max-width: 350px"
               ShowTimePicker="true"
               AriaLabel="تاریخ"
               ShowMonthPickerAsOverlay="true"
               Placeholder="تاریخ" />`

**Comment by msynk** [comment] 2023-10-01 15:52
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue.

**Comment by msynk** [comment] 2023-10-02 18:37
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment] 2023-10-02 22:17
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Closed** 2023-10-02 22:17 UTC
Labels: area / BlazorUI

**Comment by msynk** [comment] 2023-10-17 14:27
The pre-release has been published. Please give it a try and give feedback.
