### ISSUE TITLE
BitChartTimeAxis demo of Time Carthesian chart

### ISSUE THREAD

**Issue by kpietralik** [bitfoundation/bitplatform#5116] opened 2023-08-21 20:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Can we get a working demo of BitChart using BitChartTimeAxis in x-axis? My attempts have stopped at the following exception:
```
[INFO:CONSOLE(1)] "This method is not implemented: either no adapter can be found or an incomplete integration was provided.
[chromium] Error: This method is not implemented: either no adapter can be found or an incomplete integration was provided.
[chromium]     at an.nn (https://0.0.0.0/_content/Bit.BlazorUI.Extras/chart.js/Chart.min.2.9.4.js:7:112166)
[chromium]     at n.update (https://0.0.0.0/_content/Bit.BlazorUI.Extras/chart.js/Chart.min.2.9.4.js:7:146969)
[chromium]     at ce (https://0.0.0.0/_content/Bit.BlazorUI.Extras/chart.js/Chart.min.2.9.4.js:7:80458)
[chromium]     at Object.update (https://0.0.0.0/_content/Bit.BlazorUI.Extras/chart.js/Chart.min.2.9.4.js:7:82417)
[chromium]     at tn.updateLayout (https://0.0.0.0/_content/Bit.BlazorUI.Extras/chart.js/Chart.min.2.9.4.js:7:106313)
[chromium]     at tn.update (https://0.0.0.0/_content/Bit.BlazorUI.Extras/chart.js/Chart.min.2.9.4.js:7:105922)
[chromium]     at tn.construct (https://0.0.0.0/_content/Bit.BlazorUI.Extras/chart.js/Chart.min.2.9.4.js:7:102923)
[chromium]     at new tn (https://0.0.0.0/_content/Bit.BlazorUI.Extras/chart.js/Chart.min.2.9.4.js:7:102287)
[chromium]     at s.setupChart (https://0.0.0.0/_content/Bit.BlazorUI.Extras/scripts/bit.blazorui.extras.js:1:539)
[chromium]     at https://0.0.0.0/_framework/blazor.webview.js:1:3337
[chromium]    at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16 1[[System.Boolean, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
[chromium]    at Bit.BlazorUI.BitChart.OnAfterRenderAsync(Boolean firstRender) in /home/runner/work/bitplatform/bitplatform/src/BlazorUI/Bit.BlazorUI.Extras/Components/Chart/BitChart.razor.cs:line 46
[chromium]    at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)", source: https://0.0.0.0/_framework/blazor.webview.js (1)
```

I have modified the Linear Line Chart component demo by providing:

```csharp
XAxes = new List<BitChartCartesianAxis>
{
    new BitChartTimeAxis
    {
        Distribution = BitChartTimeDistribution.Linear,
        Bounds = BitChartScaleBound.Data,
        Time = new BitChartTimeOptions
        {
            IsoWeek = true,
            Unit = BitChartTimeMeasurement.Day,
            Round = BitChartTimeMeasurement.Day,
        }
    }
},
```

and dataset1 (with dataset2 removed):

```csharp
IDataset<BitChartTimePoint> dataset1 = new BitChartLineDataset<BitChartTimePoint>(..IEnumerable of BitChartTimePoint objects..)
```

### Describe the solution you'd like

A working demo of BitChart with BitChartTimeAxis presenting Time Carthesian Chart:
https://www.chartjs.org/docs/latest/axes/cartesian/time.html

**Comment by msynk** [comment] 2023-08-22 15:32
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue.

**Comment by msynk** [comment] 2023-08-25 20:15
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment] 2023-08-26 09:31
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment] 2023-08-26 17:57
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Closed** 2023-08-26 17:56 UTC
Labels: area / BlazorUI

**Comment by msynk** [comment] 2023-08-26 19:05
The pre-release has been published. Please give it a try and give feedback.
