### ISSUE TITLE
Documentation has broken alignment

### ISSUE THREAD

**Issue by linkdotnet** [bitfoundation/bitplatform#2859] opened 2022-08-02 19:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If you go to https://components.bitplatform.dev/components/numeric-text-field the input fields are a bit misaligned.

![image](https://user-images.githubusercontent.com/26365461/182454265-63e73be7-bf0b-4130-ae03-8fa5714fdf03.png)

### Expected Behavior

The alignment works exactly like the other documentation pages.

**Comment by msynk** [comment] 2022-08-02 19:41
@linkdotnet thanks for submitting this issue
we will look into this problem and plan a fix for the issue.

**Comment by msynk** [comment] 2022-08-02 19:43
duplicate of #2781

**Closed by msynk** 2022-08-02 19:43 UTC
