### ISSUE TITLE
UI doesn't remove chips/items in `BitDropdown` while `Virtualize` is set to true

### ISSUE THREAD

**Issue by artinzamani** [bitfoundation/bitplatform#8831] opened 2024-10-06 09:11 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I cannot remove chips while `Virtualization` is set to true on a `BitDropdown` component.
It seems that the underlying `Values` work as expected on remove, but the UI is not updated.
The behavior is the same for individual chips close button as well as the whole dropdown clear button.

### Steps To Reproduce

Here's a minimal example:

```csharp
<BitDropdown Chips
             ShowClearButton
             Combo
             Virtualize
             IsMultiSelect
             ItemsProvider="LoadItems"
             TItem="BitDropdownItem<string>" TValue="string" />

@code {
    private async ValueTask<BitDropdownItemsProviderResult<BitDropdownItem<string>>> LoadItems(
        BitDropdownItemsProviderRequest<BitDropdownItem<string>> request)
    {
        List<BitDropdownItem<string>> items =
        [
            new BitDropdownItem<string>
            {
                Text = "Foo",
                Value = "foo"
            },
            new BitDropdownItem<string>
            {
                Text = "Bar",
                Value = "bar"
            }
        ];
        return BitDropdownItemsProviderResult.From(items, items!.Count);
    }
}
```

### .NET Version

8.0.401

### Anything else?

Bit.BlazorUI v8.11.0
Blazor Server

**Comment by msynk** [comment] 2024-10-06 09:23
@artinzamani Thanks for contacting us.
We're investigating this issue. We'll let you know if it's possible to work on this issue.

**Comment by msynk** [comment] 2024-10-09 16:18
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment] 2024-10-09 16:19
Resolving this issue has started. It will be announced when this issue is resolved.

**Closed** 2024-10-09 19:27 UTC
Labels: area / BlazorUI

**Comment by artinzamani** [comment] 2024-10-10 00:05
Kudos for the quick follow up.
I have immense respect for the great work you are doing.
