### ISSUE TITLE
[Hybrid] Statusbar and Titlebar theme is not sync with UI

### ISSUE THREAD

**Issue by mhrastegari** [bitfoundation/bitplatform#4478] opened 2023-05-30 13:09 UTC
### Screenshot
![image](https://github.com/bitfoundation/bitplatform/assets/42671084/35b4cf25-382c-4e55-bd80-fb45b0ee0366)

**Comment by msynk** [comment] 2023-06-14 15:59
duplicate of #4534

**Closed by msynk** 2023-06-14 15:59 UTC
Labels: area / components, area / templates
