### ISSUE TITLE
`BitSwiper` item position

### ISSUE THREAD

**Issue by mhrastegary77** [bitfoundation/bitplatform#2962] opened 2022-08-11 08:30 UTC
### Summary
When we're on small screen size and scroll the BitSwiper to the last item, if we resize the browser to larger width the last items sticks on its position and doesn't adapt its self to the screen size.

### Expected result
BitSwiper adapts to screen sizes.

### Screenshots

https://user-images.githubusercontent.com/42671084/184093946-c3a2e02a-8b9f-480a-843d-c186acab9edd.mp4

**Comment by msynk** [comment] 2022-08-14 09:05
We're investigating your issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment] 2022-08-14 09:13
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment] 2022-08-14 09:13
Resolving this issue has started. It will be announced when this issue is resolved.

**Closed** 2022-08-14 09:33 UTC

**Comment by msynk** [comment] 2022-08-14 09:49
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Comment by msynk** [comment] 2022-08-14 13:22
The pre-release has been published. Please give it a try and give feedback.
