### ISSUE TITLE
Need prefix options for `ChoiceGroup` for indexing the choice group items

### ISSUE THREAD

**Issue by samdubey** [bitfoundation/bitplatform#5605] opened 2023-10-17 09:23 UTC
Dear Team,

We need a prefix option for ChoiceGroup items as a number / alphanumeric or an image:

![image](https://github.com/bitfoundation/bitplatform/assets/6169846/902cf610-835b-406e-84bd-4e38fba18efb)

**Comment by msynk** [comment] 2023-10-17 09:42
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue.

**Comment by msynk** [comment] 2023-10-17 09:42
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment] 2023-10-17 09:43
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment] 2023-10-17 14:25
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Closed** 2023-10-17 14:25 UTC
Labels: area / BlazorUI

**Comment by msynk** [comment] 2023-10-17 19:35
The pre-release has been published. Please give it a try and give feedback.
