### ISSUE TITLE
`MessageBox` and `ConfirmMessageBox` issue in `BlazorServer`

### ISSUE THREAD

**Issue by ParsaLmn** [bitfoundation/bitplatform#5150] opened 2023-08-26 11:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

hi.
I have signed in to an account in admin template project with chrome.
and then I tried to sign in to another account with firefox ,
 when a bad request exception happens it shows the exception in both browsers.

### .NET Version

7

**Comment by msynk** [comment] 2023-08-26 14:44
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue.

**Comment by msynk** [comment] 2023-08-26 15:13
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment] 2023-08-26 15:20
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by ysmoradi** [comment] 2023-08-26 15:30
This is a known issue and `MessageBox` and `ConfirmMessageBox` components will be replaced with `DialogBox` in Bit.BlazorUI in near future.

For our production, we recommend `BlazorWebAssembly` in `Pwa`, `PwaPrerender`, and `SpaPrerender` modes alongside `BlazorHybrid` for `Android`, `iOS`, `Windows`, `macOS`, and `BlazorElectron` for `Windows`, `macOS`, `Linux`.

However, I'm addressing this issue in a PR. If you encounter any other issues on `BlazorServer`, let us know so we can resolve it quickly.

**Comment by ysmoradi** [comment] 2023-08-26 16:08
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

Meanwhile you can port either AdminPanel, TodoTemplate or BlazorDual changes from #5151 to your project.

**Closed** 2023-08-26 16:28 UTC
Labels: area / templates

**Comment by msynk** [comment] 2023-08-26 19:04
The pre-release has been published. Please give it a try and give feedback.
