### ISSUE TITLE
RTL feature for `BitDropDown`

### ISSUE THREAD

**Issue by msangtarash** [bitfoundation/bitplatform#3445] opened 2022-10-25 10:14 UTC
![image](https://user-images.githubusercontent.com/23101977/197746866-e088aab1-69e5-4295-962a-d92d7024ac0b.png)

I need to be able to use `BitDropDown` in this way.
but RTL is not working fine.
could you please add the RTL feature

**Comment by msynk** [comment] 2022-10-27 10:38
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment] 2022-10-27 10:51
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment] 2022-10-30 15:01
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment] 2022-10-31 02:02
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Closed** 2022-10-31 02:01 UTC
Labels: area / components
