### ISSUE TITLE
By tapping on `BitDropDown` with search bar, search bar is not focused 

### ISSUE THREAD

**Issue by msangtarash** [bitfoundation/bitplatform#3391] opened 2022-10-19 15:07 UTC
I am using  `BitDropDown` and set ShowSearchBox="true", I expect by tapping on it, the search bar focused 
 but I need to tap on it and then tap on the search bar to focus on the search bar

**Comment by msynk** [comment] 2022-10-19 17:43
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment] 2022-10-19 17:46
automatically focusing the searchbox is not always appropriate. for example on a phone it causes the keyboard to be opened which is not a good experience for users each time they open a dropdown they also see a keyboard opened.
we decided to add a new boolean parameter to enable this auto-focus behavior.

**Comment by msynk** [comment] 2022-10-19 17:46
The issue is accepted and planned. Resolving it will start ASAP.

**Closed** 2022-10-22 18:12 UTC
Labels: area / components, enhancement

**Comment by msynk** [comment] 2022-10-31 15:44
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Comment by msynk** [comment] 2022-10-31 15:45
The pre-release has been published. Please give it a try and give feedback.

**Comment by msangtarash** [comment] 2022-11-30 15:00
Thank you for the changes :)
