### ISSUE TITLE
`BitCarusal` with size formatting issue.

### ISSUE THREAD

**Issue by msangtarash** [bitfoundation/bitplatform#3588] opened 2022-11-29 08:13 UTC
I am using `BitCarusal`, as you see in the image the width of it is not recognized well
![image](https://user-images.githubusercontent.com/23101977/204474851-91d4eb8a-6923-4fd2-a0e2-a5859bbe81f6.png)

**Comment by msynk** [comment] 2022-11-29 12:51
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment] 2022-12-02 08:44
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment] 2022-12-04 18:05
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment] 2022-12-04 19:35
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment] 2022-12-04 20:21
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Closed** 2022-12-04 20:20 UTC
Labels: area / components

**Comment by msynk** [comment] 2023-02-07 23:34
The pre-release has been published. Please give it a try and give feedback.
