### ISSUE TITLE
Minor documentation issue / broken link in todo template

### ISSUE THREAD

**Issue by kg** [bitfoundation/bitplatform#4836] opened 2023-07-27 10:21 UTC
The todo template's readme recommends going to https://bitplatform.dev/todo-template/getting-started for information on how to build it, but that link is a 404.

**Comment by msynk** [comment] 2023-07-27 12:55
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment] 2023-07-27 12:59
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment] 2023-07-27 18:50
Resolving this issue has started. It will be announced when this issue is resolved.

**Closed** 2023-07-27 20:48 UTC
Labels: area / websites

**Comment by msynk** [comment] 2023-07-27 20:50
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.
