### ISSUE TITLE
Cancel selected value issue in the BitDropDown component

### ISSUE THREAD

**Issue by rypedram** [bitfoundation/bitplatform#4022] opened 2023-03-02 09:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

bit-dropdown seems to have no cancel button 

you can see on this https://components.bitplatform.dev/components/drop-down

### Expected Behavior

expected to have a cancel button for clear selected value 

### .NET Version

6.0.200

**Comment by msynk** [comment] 2023-03-02 09:38
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment] 2023-03-02 09:47
you can simply reset the value of the variable two-way-bound to the `Value` parameter, like this:

```razor
<BitDropDown ... @bind-Value="myValue" />
<BitButton OnClick="() => myValue = null">Reset</BitButton>
```

**Comment by rypedram** [comment] 2023-03-02 09:57
thanks; :) 
 it would be better if bitdropDown has a cancel button like BitDatePicker

**Comment by msynk** [comment] 2023-03-02 10:21
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment] 2023-03-16 17:42
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment] 2023-03-18 13:53
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Closed** 2023-03-18 13:52 UTC
Labels: area / components

**Comment by msynk** [comment] 2023-05-24 23:59
The pre-release has been published. Please give it a try and give feedback.
