### ISSUE TITLE
Add EventCallback to close button in dropdown

### ISSUE THREAD

**Issue by mostafa1374** [bitfoundation/bitplatform#7243] opened 2024-03-26 06:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I need a callback event for the close button on the dropdown to clear the filter I set on it.

### Describe the solution you'd like

A EventCallback should be placed in the HandleOnClearClick method

```
private async Task HandleOnClearClick()
{
    if (IsEnabled is false) return;

    if (IsMultiSelect)
    {
        if (ValuesHasBeenSet && ValuesChanged.HasDelegate is false) return;

        Values = Array.Empty<TValue?>();
    }
    else
    {
        if (ValueHasBeenSet && ValueChanged.HasDelegate is false) return;

        CurrentValue = default;
    }

    UpdateSelectedItemsFromValues();
    await OnClickClearButton.InvokeAsync(); // This Section needed
}
```

**Comment by msynk** [comment] 2024-03-26 06:46
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue.

**Comment by msynk** [comment] 2024-03-29 08:41
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment] 2024-03-29 08:41
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment] 2024-03-29 08:44
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Closed** 2024-03-29 08:43 UTC

**Comment by msynk** [comment] 2024-03-29 08:47
@mostafa1374 
we've added a call to the `OnChange` event with a null value, so you can capture this change by registering a handler.

**Comment by msynk** [comment] 2024-05-23 20:47
The pre-release has been published. Please give it a try and give feedback.
