### ISSUE TITLE
Add custom increments and decrements for hours and minutes in TimePicker

### ISSUE THREAD

**Issue by mostafa1374** [bitfoundation/bitplatform#7125] opened 2024-03-13 07:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I was trying to increase or decrease the minutes for the time picker so that the user can change the time by increasing or decreasing by 15 minutes.

![image](https://github.com/bitfoundation/bitplatform/assets/25504875/a4392622-5031-4a10-9269-fbe65e98698a)
![image](https://github.com/bitfoundation/bitplatform/assets/25504875/a1e23082-9af2-4124-bc02-c7b354c30e31)

### Describe the solution you'd like

In the ChangeMinute and ChangeHour methods, within the increase and decrease sections, a property must be received. Based on this property, the value should either increase or decrease

for example:
```
private async Task ChangeMinute(bool isNext)
{
    if (isNext)
    {
        if (_minute < 59)
        {
            _minute += myPropsMin; // This Section
        }
        else
        {
            _minute = 0;
        }
    }
    else
    {
        if (_minute > 0)
        {
            _minute -= myPropsMin; // This Section
        }
        else
        {
            _minute = 59;
        }
    }

    await UpdateCurrentValue();
}
```

### Additional context

for Hour:
```
private async Task ChangeHour(bool isNext)
{
    if (isNext)
    {
        if (_hour < 23)
        {
            _hour += MyPropHour // this section;
        }
        else
        {
            _hour = 0;
        }
    }
    else
    {
        if (_hour > 0)
        {
            _hour -= MyPropHour // this section;
        }
        else
        {
            _hour = 23;
        }
    }

    await UpdateCurrentValue();
}
```

**Comment by msynk** [comment] 2024-03-13 16:51
@mostafa1374 Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue.

**Comment by msynk** [comment] 2024-03-14 09:36
The issue is accepted and planned. Resolving it will start ASAP.

**Closed** 2024-03-15 10:34 UTC
Labels: area / BlazorUI

**Comment by msynk** [comment] 2024-03-15 10:35
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Comment by msynk** [comment] 2024-05-23 20:45
The pre-release has been published. Please give it a try and give feedback.
