### ISSUE TITLE
Cannot set the InfiniteSliding in BitCarousel to false

### ISSUE THREAD

**Issue by mhrastegary77** [bitfoundation/bitplatform#2817] opened 2022-07-30 09:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When we set `InfiniteSliding="false"` nothing happens and items keep scrolling inifinitly.

### Expected Behavior

When we set `InfiniteSliding="false"`  items not keep scrolling inifinitly.

**Comment by ysmoradi** [comment] 2022-07-30 09:24
Do we've such a parameter? Have a look at `IsSlideShow` (yeah I know it has a ridiculous name), it might work for you

**Comment by mhrastegary77** [comment] 2022-07-30 09:30
there's no such thing in properties of BitCarousel tag

**Comment by ysmoradi** [comment] 2022-07-30 11:20
The issue is accepted and planned. Resolving it will start ASAP.

https://github.com/bitfoundation/bit-components-playground/blob/master/src/client/Pages/Issues/2817/Index.razor

@sajadkardel

**Comment by msynk** [comment] 2022-07-30 16:49
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment] 2022-07-30 21:15
@mhrastegary77 
the incorrect parameter name is changed to the correct name of `InfiniteScrolling`

**Comment by mhrastegary77** [comment] 2022-07-31 01:32
Thank you Saleh ❤️ 
I really deeply mean that :)

**Closed** 2022-07-31 05:11 UTC
Labels: area / components

**Comment by msynk** [comment] 2022-07-31 05:13
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Comment by msynk** [comment] 2022-08-14 09:51
The pre-release has been published. Please give it a try and give feedback.
