### ISSUE TITLE
wrong snipet for adding bit script

### ISSUE THREAD

**Issue by mr-rahimi** [bitfoundation/bitplatform#2440] opened 2022-07-09 19:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the script tag is not self-closing while in the guide to add the blazer-UI, it is self-closing.
![image](https://user-images.githubusercontent.com/10692091/178119487-db249a70-9edc-4ae0-982a-d093a5b74c85.png)

### Expected Behavior

it should be like this:
<script src="_content/Bit.BlazorUI/scripts/bit.blazorui.min.js"></script>

**Comment by ysmoradi** [comment] 2022-07-09 19:12
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment] 2022-07-09 19:56
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment] 2022-07-09 20:05
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Closed** 2022-07-09 20:04 UTC
Labels: area / components, high priority

**Comment by ysmoradi** [comment] 2022-07-11 15:14
The pre-release has been published. Please give it a try and give feedback
