### ISSUE TITLE
`BitPivot` Add placement property for tabs placements

### ISSUE THREAD

**Issue by NGame1** [bitfoundation/bitplatform#3231] opened 2022-09-16 11:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

I need a property, like Placement to set the placement of the tab headers. 
Placement= Top/Bottom is more needed I think and Left, Right ones are can act like a sidebar.
Here is a sample from Syncfusion Tabs control:
https://blazor.syncfusion.com/demos/tabs/orientation?theme=fabric&_gl=1*1l50e1h*_ga*MTQwMzg4ODc4LjE2NjAzMTQyODY.*_ga_WC4JKKPHH0*MTY2MzMyNzUyNy4yNS4xLjE2NjMzMjc2NTIuMC4wLjA.&_ga=2.249441223.1304948410.1663327513-140388878.1660314286

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/19765248/190629751-3167035d-7253-4ebe-bf04-bc1e38a754df.png">

**Comment by msynk** [comment] 2022-09-17 15:48
@NGame1 Thanks for submitting this issue.
We're investigating your issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment] 2022-12-02 08:41
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment] 2022-12-24 16:03
@NGame1 
while we are working on adding this feature, you can use the `Render content separately` feature shown on the demo page to render the content anywhere you want:
https://components.bitplatform.dev/components/pivot#example7

**Comment by msynk** [comment] 2022-12-25 11:56
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment] 2022-12-28 18:41
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Closed** 2022-12-28 18:41 UTC
Labels: area / components

**Comment by msynk** [comment] 2023-02-07 23:32
The pre-release has been published. Please give it a try and give feedback.
