### ISSUE TITLE
Horizontal Scrolling within Menu on all Platforms not possible.

### ISSUE THREAD

**Issue by techscx** [bitfoundation/bitplatform#6346] opened 2023-12-18 09:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Horizontal Scrolling within Menu on all Platforms not possible.
On IOS, Android in portrait Mode, and on Windows in any mode scrolling is captured by the content page. When trying to scroll on the left-side Menue, only the content of the page is scrolling.

### Expected Behavior

The menu should be scrollable in portrait mode.

### Steps To Reproduce

Tried with v-8.4.0

### .NET Version

8.0.100

**Comment by techscx** [comment] 2023-12-18 10:55
Same applies to all Maui-Android and Maui-Windows. Untestet: Maui-Catalyst.

**Comment by msynk** [comment] 2023-12-18 14:31
@techscx Thanks for contacting us.
The issue is not clear to us. what component/tooling do you have this problem with? what is this menu?

**Comment by techscx** [comment] 2023-12-18 16:29
> @techscx Thanks for contacting us. The issue is not clear to us. what component/tooling do you have this problem with? what is this menu?

Ah, sorry I have forgotten to  mention: It is the admin-panel. The Left Vertical Menu. Once, it does not fit in the current window, it should be scrollable. Please refer to the screenshot:
<img width="299" alt="2023-12-18-172659-640-SHOT" src="https://github.com/bitfoundation/bitplatform/assets/71921910/0b32028b-c7bb-43a3-aba8-27170c5c2213">

**Comment by msynk** [comment] 2023-12-19 08:21
@techscx Thanks for clarification. so you mean the `Vertical` scrolling of the menu on small screens is not possible.
we are investigating this issue now.

**Comment by msynk** [comment] 2023-12-23 08:14
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment] 2023-12-23 08:34
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment] 2023-12-23 18:47
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Closed** 2023-12-23 18:47 UTC
Labels: area / templates

**Comment by msynk** [comment] 2024-05-23 20:38
The pre-release has been published. Please give it a try and give feedback.

**Comment by techscx** [comment] 2024-05-24 22:52
Hello, I can confirm that scrolling is fixed. Thank You!

**Comment by msynk** [comment] 2024-05-24 23:02
Glad to hear that this helped.
Thanks for choosing the bit platform products.
