### ISSUE TITLE
FreeSwipe property in BitCarousel

### ISSUE THREAD

**Issue by zahrabayatt** [bitfoundation/bitplatform#2830] opened 2022-07-31 07:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

The current implementation of BitCarousel doesn't have option for free swipe, not per item(ScrollItemsCount

https://user-images.githubusercontent.com/45567233/182014506-9afe92a3-9b6a-4746-b596-26a49cd3f369.mp4

)

**Comment by msynk** [comment] 2022-07-31 08:13
@zahrabayatt thanks for submitting this issue.
this swipe feature is impossible or very hard to implement for our carousel.
the one you showed in the video, is not an actual carousel, it's just a series of elements that can scroll freely.

**Comment by msynk** [comment] 2022-07-31 08:19
we might be able to add this feature only when the InfiniteScrolling is disabled.

**Comment by msynk** [comment] 2022-07-31 08:19
We're investigating your issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by zahrabayatt** [comment] 2022-07-31 13:13
> InfiniteScrolling is disabled.

but we comfortable to disabled the InfiniteScrolling.

**Comment by zahrabayatt** [comment] 2022-07-31 13:15
> We're investigating your issue. We'll let you know if it's possible to work on this issue or not.

Thanks a lot

**Comment by msynk** [comment] 2022-08-07 09:24
The issue is accepted and planned. Resolving it will start ASAP.
we decided to implement a new component for this requirement (#2877)

**Comment by msynk** [comment] 2022-08-07 12:45
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment] 2022-08-07 13:45
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Comment by msynk** [comment] 2022-08-07 13:46
#2912

**Closed** 2022-08-07 13:45 UTC
Labels: area / components, feature

**Comment by msynk** [comment] 2022-08-14 09:52
The pre-release has been published. Please give it a try and give feedback.
