### ISSUE TITLE
Implement a new button component with loading

### ISSUE THREAD

**Issue by msangtarash** [bitfoundation/bitplatform#3501] opened 2022-11-07 09:50 UTC
I need to show the loading on the button and make it disabled while a task is running.

**Comment by msynk** [comment] 2022-11-07 10:54
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment] 2022-11-08 10:32
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment] 2022-11-10 10:00
Resolving this issue has started. It will be announced when this issue is resolved.

**Closed** 2022-11-11 18:14 UTC
Labels: area / components

**Comment by msynk** [comment] 2022-11-15 21:03
The pre-release has been published. Please give it a try and give feedback.
