### ISSUE TITLE
Responsive problem in medium screen size on the `Bit.BlazorUI` Home page

### ISSUE THREAD

**Issue by sajadkardel** [bitfoundation/bitplatform#2954] opened 2022-08-10 11:32 UTC
<img width="773" alt="Untitled" src="https://user-images.githubusercontent.com/62190682/183888617-77126d69-cea4-4e73-abdf-534bc88ab45c.png">

**Comment by msynk** [comment] 2022-08-10 15:38
there is no problem. it is by design. so I'm closing this issue.

**Closed by msynk** 2022-08-10 15:38 UTC
