### ISSUE TITLE
The DateRangePicker component in the Persian calendar does not display the selected date correctly

### ISSUE THREAD

**Issue by MeysamBahadori** [bitfoundation/bitplatform#3386] opened 2022-10-18 09:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The DateRangePicker component does not display the selected date range correctly (In the Persian calendar )
![image](https://user-images.githubusercontent.com/107020266/196393631-b106a735-a613-4b1d-ba3e-bfed7a08487b.png)

### .NET Version

6.0.400

### Anything else?

Bit.BlazorUI : 4.4.0-pre-01

**Comment by msynk** [comment] 2022-10-18 14:33
Thanks for contacting us. We're investigating your issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment] 2022-10-18 17:30
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment] 2022-10-23 19:57
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment] 2022-10-23 20:00
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Closed** 2022-10-23 20:00 UTC
Labels: area / components

**Comment by msynk** [comment] 2022-10-31 15:41
The pre-release has been published. Please give it a try and give feedback.
