### ISSUE TITLE
Add IsRequired for `BitNumericTextField`

### ISSUE THREAD

**Issue by msangtarash** [bitfoundation/bitplatform#5689] opened 2023-10-19 08:48 UTC
We need to set `IsRequired` for `BitNumericTextField`.

**Comment by msynk** [comment] 2023-10-19 08:53
The `NumericTextField` does not support null values by design, and the default value is 0.
So basically, its value is always required, and having this parameter is rather meaningless.
If you need a specific behavior in this component, please describe it.

**Comment by msangtarash** [comment] 2023-10-22 11:09
We have an edit form in which there is a property by type of nullable double In some scenarios it is required to enter a value for it in other scenarios it is not required,
and also I want to show the star in its label that is handheld by IsRquired in other components.

**Comment by msynk** [comment] 2023-10-22 11:25
I understand the requirements, but changing the current behavior of the `BitNumericTextField` may take too long. I suggest using the `BitTextField` for now which has what you require.

**Comment by msynk** [comment] 2023-10-22 11:27
I'm closing this issue in favor of #5758

**Closed by msynk** 2023-10-22 11:27 UTC
