### ISSUE TITLE
Hide the first navigation button for the first view

### ISSUE THREAD

**Issue by hootanht** [bitfoundation/bitplatform#2840] opened 2022-07-31 13:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

In the first implementation of `Bit Carousel` we see two buttons for the navigation between items, but we don't want to see the first button of the list in that. 

### Describe the solution you'd like

We can set parameter to `Bit Carousel` for showing or hiding first button in the list or not

**Comment by msynk** [comment] 2022-07-31 18:43
@hootanht 
If I get your request correctly, do you want to have the navigation buttons (Prev/Next) to be disabled at their corresponding end of the carousel, if the InfiniteScrolling is false?
for example, the Prev button should be disabled/hidden at the start?

**Comment by hootanht** [comment] 2022-08-01 03:21
> @hootanht 
> If I get your request correctly, do you want to have the navigation buttons (Prev/Next) to be disabled at their corresponding end of the carousel, if the InfiniteScrolling is false?
> for example, the Prev button should be disabled/hidden at the start?

Yes, absolutely correct.

**Comment by msynk** [comment] 2022-08-01 12:07
We're investigating your issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment] 2022-08-02 07:09
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment] 2022-08-02 07:46
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment] 2022-08-02 08:32
The issue has been resolved.
Note that in this state, the issue itself gets closed.

**Closed** 2022-08-02 08:31 UTC
Labels: area / components, feature

**Comment by msynk** [comment] 2022-08-14 09:52
The pre-release has been published. Please give it a try and give feedback.
