### ISSUE TITLE
Bit.BlazorUI Consumers be able to bind BitTextFild upon specific DOM event , like  @bind:event="{EVENT}"

### ISSUE THREAD

**Issue by ShahryarSaljoughi** [bitfoundation/bitplatform#7660] opened 2024-06-01 06:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Problem I faced:
When a web application created using Bit.Boilerplate is deployed, as I type into a `BitTextField` the characters are randomly removed or displayed with delay, on first visit(s).

## Solutions suggested by others:
I digged a bit, seems like it is not actually a bug of Bit, but related to how Blazor Auto works. However, the current Implementation of Bit.BlazorUI components does not allow the common workarounds.  
### workarounds suggested by others:  
- Use debouncing
- Bind upon `onchange` instead of `oninput`

I see that currently you're working on throttle and debounce features for inputs. But I'm not sure how to use them when they are released in new versions of nuget packages. Is there any way I can use them before they are released?  

Is there anyway I can configure `BitTextField` not to do anything `oninput` ?

## What is the underlying related problem:
Let's say app is running with `AppRenderMode.Auto` set globally. On first visit web socket is in charge of handling UI updates and depends on communication with server. As I type into a text field updating UI is slower than the my typing speed, so a race condition occrs between the values emited from server to display, and the values I've just entered into the text box.  
Here is the related issue of asp.net core repo: https://github.com/dotnet/aspnetcore/issues/14242

The sitution is actualy annoyin just when **updates are occuring upon `oninput` event**, and the problem can be ceased if we change the binding event to `onchange` instead of `oninput`. However currently `BitTextField` is silmulating the binding behavior using both `oninput` and `onchange`.

## Feature I need:
I need to be able to change `oninput` event handler of `BitTextField`. Using this feature I can have a smoother experience when interactivity location is on server. 

### Additional context

I copied this gif from the related issue on aspnetcore repository:
![65398678-770c9d80-dd6d-11e9-9d57-ea6b83947363 1](https://github.com/bitfoundation/bitplatform/assets/11381298/a9ce70fe-b0a0-4c18-bbe1-568aad94c8c3)

As evident, some characters vanish after being typed, subsequently reappearing. This forces me to type at an unnaturally slow speed.

**Comment by ysmoradi** [comment] 2024-06-01 07:53
That's because you're hosting on blazor server that we don't recommend at all for production and blazor server is mainly supported for dev environment related stuffs such as .NET hot reload etc.

Note that using more than 47 features and 58 components in Boilerplate, cost your users downloading only 4MB in blazor web assembly mode (Unless you use charts and/or offline client side database features), and it also supports pre-rendering and/or PWA.

**Comment by ShahryarSaljoughi** [comment] 2024-06-01 10:14
Hi. Hope you do well. Sorry I was not specific and clear enough. I'm deploying with **`AppRenderMode.Auto`**. On first visits while assets are not downloaded yet, the issue occurs. 
I was thinking about changing to blazor web assembly mode though, I thought solving this issue could help keep Auto remder mode with its fast load time.

**Comment by ShahryarSaljoughi** [comment] 2024-06-01 10:17
For now I've changed the render mode from being globally set, to per component mode, and used web assembly for components having forms, keeping Auto render mode for the rest of pages.

**Comment by msynk** [comment] 2024-06-01 13:00
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by ShahryarSaljoughi** [comment] 2024-06-02 05:49
that would effectively help the underlying problem, and seems even better than my two suggested solutions.  
Title of issue is not aligned with what really is gonna be done based on this issue. (misleading, not searchable)
I'll edit the initial feature request title to be aligned with what you've planned to do.

**Comment by msynk** [comment] 2024-06-17 12:27
Resolving this issue has started. It will be announced when this issue is resolved.

**Closed** 2024-06-20 05:54 UTC
Labels: area / BlazorUI
