### ISSUE TITLE
How to change the `The Date field is not valid` validation message to another language for date picker?

### ISSUE THREAD

**Issue by Kamalifar** [bitfoundation/bitplatform#3629] opened 2022-12-18 05:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

The users get this validation message from DatePicker if they do not follow the correct format.
**The Date field is not valid**.
How do I change the validation message to another language?

**Comment by msynk** [comment] 2022-12-18 09:17
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment] 2022-12-18 09:21
@Kamalifar 
The Bit BlazorUI validation is implemented based on the ASP.NET validation infrastructure, so I believe all of the validation messages come from the Model and their validation attributes, such as [Required].

Could you please submit the code and image of your issue for a better understanding of your problem?

**Comment by Kamalifar** [comment] 2022-12-18 09:42
@msynk Thank you for quick response. 
I give the English validation message even if I apply a regex attribute with Persian error message on the model field (Date).
![B45TB](https://user-images.githubusercontent.com/35212420/208291313-b9d81069-8c7c-45a1-85d8-f7b5386067db.png)
<BitDatePicker @bind-Value="Model.Date"
                                       AllowTextInput="true"
                                       FormatDate="yyyy/M/d"
                                       GoToToday="Today" Placeholder="Insert date here"
                                       Culture="PersianCultureHelper.GetFaIrCultureByFarsiNames()"
                                       Style="width:150px; display:inline-block;">
</BitDatePicker>

**Comment by msynk** [comment] 2022-12-18 10:11
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by Kamalifar** [comment] 2022-12-20 06:33
I found a [trick](https://stackoverflow.com/a/74842548/4444757), but it isn't a clean solution, However, I think that it can help you to resolving ASAP.

**Comment by msynk** [comment] 2022-12-20 08:12
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment] 2022-12-20 13:11
@Kamalifar 
We are going to add a new parameter named `InvalidErrorMessage` to customize the default error message.

**Comment by msynk** [comment] 2022-12-20 13:12
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Closed** 2022-12-20 13:11 UTC
Labels: area / components

**Comment by msynk** [comment] 2023-02-07 23:36
The pre-release has been published. Please give it a try and give feedback.
