### ISSUE TITLE
The number of total downloads of packages on bitplatform website is not up to date

### ISSUE THREAD

**Issue by zahra-yousefi** [bitfoundation/bitplatform#5345] opened 2023-09-26 09:35 UTC
as you can see in the following image the number of downloads which is +3.5M at the moment is not up to date:

![image](https://github.com/bitfoundation/bitplatform/assets/15306395/0feb5369-7544-4b48-b7cc-2f96e0ff62b8)

**Comment by msynk** [comment] 2023-09-26 09:36
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue.

**Comment by msynk** [comment] 2023-09-26 10:03
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment] 2023-09-26 10:16
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment] 2023-09-26 11:27
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Closed** 2023-09-26 11:27 UTC
Labels: area / websites

**Comment by msynk** [comment] 2023-10-17 14:27
The pre-release has been published. Please give it a try and give feedback.
