### ISSUE TITLE
Incorrect inline style for `BitDropDown` component

### ISSUE THREAD

**Issue by saleh-ghezelbash** [bitfoundation/bitplatform#2415] opened 2022-07-07 06:23 UTC
I think the `BitDropDown` component styles are not set correctly in mobile mode because they don't take the full width and height of the mobile screen. 
It is better to let the display mode be its normal and standard mode.
Or if the decision has been made, then please use `Class` instead of `Inline style` so that it can be easily modified.

**Comment by msynk** [comment] 2022-07-07 11:54
the current style in long & small screens:

![image](https://user-images.githubusercontent.com/6169846/177767164-7952ebad-2914-4ea5-8c36-e5619251cc7f.png)

**Comment by msynk** [comment] 2022-07-07 12:33
@saleh-ghezelbash 
We're investigating your issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment] 2022-07-07 17:11
@saleh-ghezelbash 
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by maryamhdr** [comment] 2022-07-07 17:32
@saleh-ghezelbash 
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by maryamhdr** [comment] 2022-07-07 19:25
@saleh-ghezelbash 
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Closed** 2022-07-08 05:20 UTC
Labels: area / components, high priority, enhancement

**Comment by maryamhdr** [comment] 2022-07-09 07:11
@saleh-ghezelbash 
The pre-release has been published. Please give it a try and give feedback.
