### ISSUE TITLE
Add a class parameter in BitBreadcrumbItems

### ISSUE THREAD

**Issue by SomayeEbrahimi** [bitfoundation/bitplatform#3421] opened 2022-10-23 06:33 UTC
- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I need to assign a specific style to one of none active BitBreadcrumbItems, but there is no option.

To make this more precise, I'm attempting to implement something like this:

![breadcrumb](https://user-images.githubusercontent.com/46419023/197377043-01a9d6b2-d1f0-4d4a-adad-59348e5f1686.JPG)

### Describe the solution you'd like

I wonder if you can add a new parameter in BitBreadcrumbItem class to apply a specific style to the desired item.

**Comment by msynk** [comment] 2022-10-23 07:17
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment] 2022-12-05 11:50
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment] 2022-12-05 11:51
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment] 2022-12-05 18:55
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Closed** 2022-12-05 18:54 UTC
Labels: area / components

**Comment by msynk** [comment] 2023-02-07 23:32
The pre-release has been published. Please give it a try and give feedback.
