### ISSUE TITLE
The GitHub stars button at the top right corner of the bitplatform website is not linked to the repo

### ISSUE THREAD

**Issue by zahra-yousefi** [bitfoundation/bitplatform#5343] opened 2023-09-26 09:13 UTC
As you can see in the following image, the highlighted button is not a link:

![image](https://github.com/bitfoundation/bitplatform/assets/15306395/8f802fb1-78ec-4167-a8b0-e6bde35bc314)

based on our observations, most users try to go to the repo by clicking on this part of the header. so it is highly recommended to make this section a link to the repo's main page or a link to star the repo.

**Comment by msynk** [comment] 2023-09-26 10:03
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment] 2023-09-26 13:22
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Closed** 2023-09-26 13:21 UTC
Labels: area / websites

**Comment by msynk** [comment] 2023-10-17 14:27
The pre-release has been published. Please give it a try and give feedback.
