### ISSUE TITLE
support for keyboard shortcuts for BitButton

### ISSUE THREAD

**Issue by samdubey** [bitfoundation/bitplatform#6112] opened 2023-11-23 08:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Can we map Keyboard button for BitButton for example Enter for submission also Left or Right Arrow keys for navigation etc.

### Describe the solution you'd like

support Keyboard Keys for BitButton

**Comment by msynk** [comment] 2023-11-23 13:59
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue.

**Comment by msynk** [comment] 2023-11-25 11:03
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment] 2023-11-28 08:45
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment] 2023-11-28 08:47
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Comment by msynk** [comment] 2023-11-28 08:49
check out #6123 
using the `Butil` tool you can now easily register keyboard shortcuts in your Blazor apps.

**Closed** 2023-12-11 12:07 UTC
Labels: area / butil

**Comment by msynk** [comment] 2023-12-23 08:35
The pre-release has been published. Please give it a try and give feedback.
