### ISSUE TITLE
Check jwt token expiry before making a httprequest 

### ISSUE THREAD

**Issue by Kyemate** [bitfoundation/bitplatform#9186] opened 2024-11-11 14:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Because the jwt token expires every 5 minutes you get a lot of unauthorized messages in the client.

The way it works now by catching an exception every 5 minutes is bad from a performance standpoint but mainly bad design decision because the jwt expiration is an expected behavior and not an exception.

### Describe the solution you'd like

Because the jwt token expiration date is known in the client one possible solution is to check expiration date and refresh the token before making the request to the server. That should reduce the number of unauthorized messages a lot.

**Comment by ysmoradi** [comment] 2024-11-11 14:29
When do we refresh the access token?

1. When a user navigates to an authorized page during pre-rendering, and the access token is either expired or doesn’t satisfy the roles and policies of the authorized attribute, we redirect the user to the `NotAuthorized` page. In this `NotAuthorized` page, we attempt to refresh the token (as the server side does not have a refresh token available during pre-rendering).

2. If any API HTTP call returns a 401 or 403, we attempt to refresh the token.
403 => meaning the access token doesn’t meet the roles and policies of the authorized attribute

3. If a user passes an expired access token to SignalR's `AppHub`, it returns an Unauthorized error, and we then attempt to refresh the token. Connecting to AppHub **without** any access token yet still valid.

Regarding 403 responses: We try to refresh the token, as it’s possible that the user has gained the required roles and/or claims sicnce last refresh.

An error is only shown in the following cases:
1. No refresh token is available in storage.

2. A refresh token completes but results in a 401, indicating the refresh token has expired, or the user’s session no longer exists in the database *

3. A refresh token completes successfully but attempts to re-render the original page or re-send the original API request still return a 403.

The user is only redirected to the sign-in page if the current page is an authorized page.

Let me know if any additional clarification is needed.

P.S. Please test above scenarios depend on your requirements on the latest stable release that is being published right now.

**Comment by Kyemate** [comment] 2024-11-11 14:43
This is the 12p13 template running with no code changes in wasm mode.
Every single time the token expires I get this error message.
![image](https://github.com/user-attachments/assets/851f8bfb-0d9e-45a3-8861-b587ed8ef3b2)

Looking in the AuthDelegatingHandler it's clear that it tries to query the server with SendAsync before it tries to refresh the token

**Comment by ysmoradi** [comment] 2024-11-12 16:26
Resolving this issue has started. It will be announced when this issue is resolved.

**Closed** 2024-11-12 18:56 UTC
Labels: area / templates

**Comment by ysmoradi** [comment] 2024-11-12 18:58
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Comment by msynk** [comment] 2024-11-18 19:00
the new release is out now.
@Kyemate could you plz test the new version and make sure the issue is resolved?

**Comment by Kyemate** [comment] 2024-11-28 22:16
> the new release is out now. @Kyemate could you plz test the new version and make sure the issue is resolved?

Hi, sorry for late reply. The problem seemed solved but now when I tried to with the 9.1p3 template it seems to be back 
![image](https://github.com/user-attachments/assets/f0f816cc-84dd-4c3a-a08a-07814b5c4d09)

**Comment by ysmoradi** [comment] 2024-11-29 09:31
These errors are typically because you've disabled trackers, as you can see, all those failed requests are related to app insights

**Comment by Kyemate** [comment] 2024-11-29 10:04
There  are some unauthorized requests in there to 
![image](https://github.com/user-attachments/assets/0192b1c3-75bf-4d51-90d7-04cb0bd40732)

**Comment by ysmoradi** [comment] 2024-11-29 10:25
What's instrument hook? Could you please test new version on a browser with no extension installed?

**Comment by Kyemate** [comment] 2024-11-29 12:19
I tried it now with chrome without extensions and I still get the 401 error. What I do is I login, wait 5 minutes then I navigate to an authorized page like settings.

**Comment by ysmoradi** [comment] 2024-11-30 07:41
Could you please give me your email or phone number that you use to register in online todo or admin demo apps?

**Comment by Kyemate** [comment] 2024-11-30 11:20
I used the default test@bitplatform.dev account

**Comment by ysmoradi** [comment] 2024-11-30 18:26
It's not happening on my side, please do one of the followings:
1- Create new test account on demo apps, do the test again and give me your email address of that test account, so I can search logs based on your user id
OR
2- Do the test with the same test@bitplatform.dev account, but when issue happened, press Ctrl + Shift + X at the same time and give me your application session id in telemetry context (You can also click on header 7 times or open it by running the `App.showDiagnostic()` command in browser's dev tools's console)

**Comment by Kyemate** [comment] 2024-12-01 19:44
The app session id is: e8dfe9a2-0938-4ad0-ac27-a6b146fc9db6
But I'm not sure it's logged.
![image](https://github.com/user-attachments/assets/0e51ab49-ce7f-466e-bf35-050e40bc9b52)

**Comment by ysmoradi** [comment] 2024-12-01 19:56
These are being logged through both sentry and app insights
I'll keep you posted
We can also have online meeting to investigate further

**Comment by Kyemate** [comment] 2024-12-02 22:00
Alright, sure I'm up for an online meeting.

**Comment by ysmoradi** [comment] 2024-12-03 08:20
Please send me DM on https://join.skype.com/invite/uCpyryqWbUgK 
There we will schedule
