### ISSUE TITLE
Icon behavior issue in side rale in `Bit.Website.Platform` project

### ISSUE THREAD

**Issue by msangtarash** [bitfoundation/bitplatform#2953] opened 2022-08-10 10:48 UTC
![image](https://user-images.githubusercontent.com/23101977/183883064-150cf7ef-fccf-43c4-9119-fbafb4f8d01f.png)

**Comment by sajadkardel** [comment] 2022-08-10 11:10
This issue will be resolved in (#2860).

**Comment by msynk** [comment] 2022-08-10 18:38
since this is a duplicate of #2860, I'm closing it.

**Closed by msynk** 2022-08-10 18:38 UTC
Labels: enhancement, area / websites
