### ISSUE TITLE
It is not possible to scroll up or down the page while scrolling on Swiper.

### ISSUE THREAD

**Issue by aasssaa1382** [bitfoundation/bitplatform#5291] opened 2023-09-16 08:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I try to swipe, Swiper lags and touch doesn't work either. When I touch action: initial, I set it to scroll only, but the lag is still there.

> 

### Expected Behavior

It can be run without lag

### Steps To Reproduce

#

### .NET Version

7.0.400 bit platform 5.5.0 

### Anything else?

> #
/
/ #

**Comment by ysmoradi** [comment] 2023-09-16 11:43
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue.

**Comment by msynk** [comment] 2023-09-16 11:58
I think you mean swiping down/up while touching or dragging is not working, since the scroll (by mouse) is working fine.

- the dragging (by mouse) is by design like this since on a desktop it is normal.
- the swiping up & down (by touch) is definitely not working on mobile devices and it's an issue.

**Comment by msynk** [comment] 2023-09-17 08:03
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment] 2023-09-17 08:06
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment] 2023-09-17 10:37
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Closed** 2023-09-17 10:37 UTC
Labels: area / BlazorUI

**Comment by msynk** [comment] 2023-09-18 15:43
The pre-release has been published. Please give it a try and give feedback.
