### ISSUE TITLE
Add theming to the Bit `BlazorUI` project

### ISSUE THREAD

**Issue by maryamhdr** [bitfoundation/bitplatform#3544] opened 2022-11-16 13:14 UTC
The project's structure needs some changes to enable the consumers to customize the overall theme of the components.
It's better to change the structure of the project step by step by applying it to the most straightforward component (`BitButton`).
Also, a demo must be added for customizing the theme.

**Comment by msynk** [comment] 2022-11-29 07:37
duplicate of #3338

**Closed by msynk** 2022-11-29 07:37 UTC
Labels: area / components, feature
